name: publish
on:
  push:
    # tags:
#       - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    name: Release
    runs-on: self-hosted
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.8

      - name: Publish Python Package
        uses: mariamrf/py-package-publish-action@v1.0.0
        with:
          python_version: '3.9.8'
        env:
          TWINE_USERNAME: ${{ secrets.NEXUS_PYPI_USER }}
          TWINE_PASSWORD: ${{ secrets.NEXUS_PYPI_TOKEN }}
          TWINE_REPOSITORY_URL: https://repo.devops.projectronin.io/repository/ronin-pypi/
