name: "Build client and Push Tag based on version"

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.9.7'
    - name: Install dependencies and build package
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine setuptools_scm setuptools_scm_git_semver
        python setup.py sdist bdist_wheel


      - name: Read version file
        id: version_file
        uses: juliangruber/read-file-action@v1
        with:
          path: ./VERSION.txt
      - name: Echo version
        run: echo "${{ steps.version_file.outputs.content }}"


      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        tag: "${{ steps.version_file.outputs.content }}"
